version: 2
updates:
  # Backend - Bundler (Ruby on Rails)
  - package-ecosystem: bundler
    directory: "/backend"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  # GitHub Actions - CI/CD workflows
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  # Frontend - NPM (React)
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
